services:
  # Frontend Service - React + Vite
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - geotrends-network

  # Backend Service - Node.js + Express
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - trends
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      # Ruta para comunicación entre contenedores Docker
      - DOCKER_URL=http://trends:5001/trends
    networks:
      - geotrends-network

  # Trends Service - Python + Flask
  trends:
    build: ./service
    ports:
      - "5001:5001"
    volumes:
      - ./service:/app
    networks:
      - geotrends-network

networks:
  geotrends-network:
    driver: bridge
